config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    root "main#index"

    # Users
    resources :users, only: [:show, :new, :create]
    get "/signup", to: "users#new", as: :signup
    get "/help", to: "main#help", as: :help

    # Sessions
    resources :sessions, only: [:new, :create, :destroy]
    get "/signin", to: "sessions#new", as: :signin
    delete "/signout", to: "sessions#destroy", as: :signout

    # Resources
    resources :themes, :images
    post '/values', to: 'values#create', as: 'create_value'  # Явное определение

    # Work
    get "work", to: "work#index"
    post "display_theme", to: "work#display_theme"
    get "image/:image_id", to: "work#show_image", as: :show_image

    # API
    namespace :api do
      get "next_image", to: "api#next_image"
      get "prev_image", to: "api#prev_image"
    end

    # Main
    get "contacts", to: "main#contacts"
    get "about", to: "main#about"
  end
end

app/models/value.rb
class Value < ApplicationRecord
  belongs_to :user
  belongs_to :image

  validates :value, 
    numericality: { 
      only_integer: true,
      in: 1..10 
    },
    presence: true

  validates :user_id, 
    uniqueness: { 
      scope: :image_id,
      message: "вы уже оценивали это изображение" 
    }
end

app/controllers/values_controller.rb
class ValuesController < ApplicationController

  def create
    @value = current_user.values.build(value_params)
    
    respond_to do |format|
      if @value.save
        update_image_average(@value.image)
        format.html { 
          redirect_back(fallback_location: root_path, notice: t('.success')) 
        }
        format.json { render json: { average: @value.image.ave_value }, status: :created }
      else
        format.html { 
          redirect_back(fallback_location: root_path, 
                      alert: @value.errors.full_messages.join(', ')) 
        }
        format.json { render json: @value.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def value_params
    params.permit(:image_id, :value)
  end
  
  def update_image_average(image)
    # Получаем среднее значение оценок через прямую связь
    average = Value.where(image_id: image.id).average(:value)
    
    # Обновляем с проверкой на наличие оценок
    image.update(ave_value: average ? average.round(2) : 0.0)
  end
end

app/helpers/values_helper.rb
module ValuesHelper
end

app/views/values/_form.html.haml
= form_for @value do |f|
  - if @value.errors.any?
    #error_explanation
      %h2= "#{pluralize(@value.errors.count, "error")} prohibited this value from being saved:"
      %ul
        - @value.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :image_id
    = f.number_field :image_id
  .field
    = f.label :value
    = f.number_field :value
  .actions
    = f.submit 'Save'

app/views/values/edit.html.haml
%h1 Editing value

= render 'form'

= link_to 'Show', @value
\|
= link_to 'Back', values_path

app/views/values/index.html.haml
%h1 Listing values

%table
  %thead
    %tr
      %th User
      %th Image
      %th Value
      %th
      %th
      %th

  %tbody
    - @values.each do |value|
      %tr
        %td= value.user_id
        %td= value.image_id
        %td= value.value
        %td= link_to 'Show', value
        %td= link_to 'Edit', edit_value_path(value)
        %td= link_to 'Destroy', value, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Value', new_value_path

app/views/values/new.html.haml
%h1 New value

= render 'form'

= link_to 'Back', values_path

app/views/values/show.html.haml
%p#notice= notice

%p
  %b User:
  = @value.user_id
%p
  %b Image:
  = @value.image_id
%p
  %b Value:
  = @value.value

= link_to 'Edit', edit_value_path(@value)
\|
= link_to 'Back', values_path