config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    root "main#index"

    # Users
    resources :users, only: [:show, :new, :create]
    get "/signup", to: "users#new", as: :signup
    get "/help", to: "main#help", as: :help

    # Sessions
    resources :sessions, only: [:new, :create, :destroy]
    get "/signin", to: "sessions#new", as: :signin
    delete "/signout", to: "sessions#destroy", as: :signout

    # Resources
    resources :themes, :images
    post '/values', to: 'values#create', as: 'create_value'  # Явное определение

    # Work
    get "work", to: "work#index"
    post "display_theme", to: "work#display_theme"
    get "image/:image_id", to: "work#show_image", as: :show_image

    # API
    namespace :api do
      get "next_image", to: "api#next_image"
      get "prev_image", to: "api#prev_image"
    end

    # Main
    get "contacts", to: "main#contacts"
    get "about", to: "main#about"
  end
end

app/views/shared/_header.html.haml
%nav
  %ul.nav.navbar-nav.pull-right
    %li.dropdown
      %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
        = t('language_name')
        %b.caret
      %ul.dropdown-menu
        - I18n.available_locales.each do |locale|
          %li= link_to t('language_name', locale: locale), url_for(locale: locale, **request.query_parameters)
    %li= link_to t('.home'), root_path
    %li= link_to t('.help'), help_path
    - if signed_in?
      %li.logged
        = current_user.email
      = gravatar_for current_user
      %li.dropdown#fat-menu
        %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
          = t('.person')
          %b.caret
        %ul.dropdown-menu
          %li= link_to t('.profile'), current_user
          %li.divider
          %li
            = button_to t('.sign_out'), signout_path, 
                method: :delete, 
                class: 'logout-link',
                form: { 'data-turbo' => 'false' }
    - else
      %li= link_to t('.sign_in'), signin_path